name: Build Docker image

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install BLAS and LAPACK for the SPAMS Python package
      run: sudo apt-get -y install libblas-dev liblapack-dev

    - name: Check out repository
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tractolearn-docker:$(date +%Y-%m-%d-%H-%M)
